all: WinDamIn WinDamOut WinDamBri

WinDamIn: parseWinDamIn.c
	gcc -o parseIn.exe parseWinDamIn.c

WinDamOut: parseWinDamOut.c
	gcc -o parseOut.exe parseWinDamOut.c

WinDamBri: parseWinDamBri.c
	gcc -o parseBri.exe parseWinDamBri.c

WinDamResults: parseWinDamResults.c
	gcc -o parseRes.exe parseWinDamResults.c